server.port=8081

spring.datasource.url=jdbc:mysql://mysql:3306/expense_db?useUnicode=true&characterEncoding=UTF-8&connectionCollation=utf8mb4_0900_ai_ci&serverTimezone=Asia/Tokyo&allowPublicKeyRetrieval=true&useSSL=false

app.upload.receipt-dir=/app/uploads/receipts

spring.thymeleaf.cache=true
